config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions:      'admins/sessions',
    passwords:     'admins/passwords',
    registrations: 'admins/registrations'
  }
  devise_for :customers, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :subjects
  resources :students
  resources :teachers
  root 'hello#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/student.rb
class Student < ApplicationRecord
end

app/models/subject.rb
class Subject < ApplicationRecord
    belongs_to :teacher
end

app/models/teacher.rb
class Teacher < ApplicationRecord
    has_many :subjects
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        case resource
        when Admin
            subjects_path          #pathは設定したい遷移先へのpathを指定してください
        when Customer
            root_path              #ここもpathはご自由に変更してください
        end
    end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
    def index
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
    before_action :authenticate_user!

    def index
        @students = Student.all
    end

    def new
        @student = Student.new
    end

    def create
        student = Student.new(student_params)
        if student.save
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end

    private
    def student_params
        params.require(:student).permit(:name, :expert, :grade)
    end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
    before_action :authenticate_user!
    def index
        @subjects = Subject.all
    end

    def new
        @subject = Subject.new
    end

    def create
        subject = Subject.new(subject_params)
        if subject.save
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end

    private
    def subject_params
        params.require(:subject).permit(:opening_year, :subject_name, :date, :start_time, :target)
    end
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
    def index
        @teachers = Teacher.all
    end

    def new
        @teacher = Teacher.new
    end

    def create
        teacher = Teacher.new(teacher_params)
        if teacher.save
        redirect_to :action => "index"
        else
        redirect_to :action => "new"
        end
    end

    private
    def teacher_params
        params.require(:teacher).permit(:name, :belonging)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/students/index.html.erb
<h1>生徒情報登録</h1>

<%= link_to "生徒情報の修正", new_student_path %>

<div class="students-container">
    <% @students.each do |t| %>
        <div class="student">
            <%= t.name %>
            <%= t.expert %>
            <%= t.grade %>
        </div>
    <% end %>
</div>

app/views/students/new.html.erb
<h1>生徒情報登録</h1>
<h3>新規</h3>
<%= form_for @student do |f| %>

    <div class="field">
        <%= f.label :名前 %>
        <%= f.text_field :name, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :所属 %>
        <%= f.select :expert, [["経営学部", "経営学部"], ["国際学部", "国際学部"], ["健康科学部", "健康科学部"], ["看護学部", "看護学部"], ["福祉学部", "福祉学部"], ["デブ", "デブ"]], include_blank: "選択して下さい" %>
    </div>

    <div class="field">
        <%= f.label :学年 %>
        <%= f.select :grade, [["１年", "１年"], ["２年", "２年"], ["３年", "３年"], ["４年", "４年"]], include_blank: "選択して下さい" %>
    </div>

    <%= f.submit "生徒情報を更新する" %>
<% end %>

<%= link_to "作成した授業一覧に戻る", students_path %>

app/views/subjects/index.html.erb
<h1>授業一覧</h1>

<%= link_to "新規投稿へ", new_subject_path %>

<div class="subjects-container">
    <% @subjects.each do |t| %>
        <div class="subject">
            <%= t.subject_name %>
            <%= t.opening_year %>
            <%= t.date %>
            <%= t.start_time %>
            <%= t.target %>
            <%= t.created_at %>
        </div>
    <% end %>
</div>

app/views/subjects/new.html.erb
<h1>授業作成</h1>

<%= form_for @subject do |f| %>
    <div class="field">
        <%= f.label :授業名 %>
        <%= f.text_field :subject_name, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :開講期 %>
        <%= f.select :opening_year, [["2021前期", "2021前期"], ["2021後期", "2021後期"], ["2022前期", "2022前期"], ["2022後期", "2022後期"], ["2023前期", "2023前期"], ["2023後期", "2023後期"]], include_blank: "選択して下さい" %>
    </div>

    <div class="field">
        <%= f.label :開講曜日 %>
        <%= f.select :date, [["月曜日", "月曜日"], ["火曜日", "火曜日"], ["水曜日", "水曜日"], ["木曜日", "木曜日"], ["金曜日", "金曜日"]], include_blank: "選択して下さい" %>
    </div>

    <div class="field">
        <%= f.label :時限 %>
        <%= f.select :start_time, [["1時限目", "1時限目"], ["2時限目", "2時限目"], ["３時限目", "３時限目"], ["4時限目", "4時限目"], ["5時限目", "5時限目"]], include_blank: "選択して下さい" %>
    </div>
    <%= f.submit "講義を作成する" %>
<% end %>

<%= link_to "作成した授業一覧に戻る", subjects_path %>

app/views/teachers/index.html.erb
<h1>教員情報登録</h1>

<%= link_to "教員情報の修正", new_teacher_path %>

<div class="teachers-container">
    <% @teachers.each do |t| %>
        <div class="teacher">
            <%= t.name %>
            <%= t.belonging %>
        </div>
    <% end %>
</div>

app/views/teachers/new.html.erb
<h1>教員情報登録</h1>
<h3>新規</h3>
<%= form_for @teacher do |f| %>

    <div class="field">
        <%= f.label :担当教員名 %>
        <%= f.text_field :name, :size => 10 %>
    </div>

    <div class="field">
        <%= f.label :所属 %>
        <%= f.select :belonging, [["経営学部", "経営学部"], ["国際学部", "国際学部"], ["健康科学部", "健康科学部"], ["看護学部", "看護学部"], ["福祉学部", "福祉学部"], ["デブ", "デブ"]], include_blank: "選択して下さい" %>
    </div>


    <%= f.submit "教員情報を更新する" %>
<% end %>

<%= link_to "作成した授業一覧に戻る", teachers_path %>